export class Customer{
    id:number;
    FirstName:string;
    MiddleName:string;
    LastName:string;
    Phone:string;
    PhoneAlt:string;
    Email:string;
    Username:string;
    Password:string;
    Address:String;
    Bank:String;
    SavingsAccountNumber:string;
    IFSCCode:string;
    ques1:string;
    ans1:string;
    ques:string;
    ans2:string;
    ques3:string;
    ans3:string;
}